views/admin_view.py
from flask import Blueprint
from flask import render_template, url_for, request, redirect, flash
from flask_login import login_user, login_required
from controllers.controllers import get_hours, check_admin
from views.admin_login import AdminLogin
from views.forms import RF_IDForm, AdminForm

admin = Blueprint('admin', __name__, template_folder='..templates')


@admin.route("/login", methods=['GET', 'POST'])
def login_admin():
    if request.method == "POST":
        user = check_admin(request.form['rf_id'])
        print(user)
        if user and user[0] == "1111":
            userlogin = AdminLogin().create(user)
            login_user(userlogin)
            flash("Вы успешно авторизовались")
            return redirect(url_for("views.index"))
        else:
            flash("Попытка входа не удалась, попробуйте снова")
    return render_template("login.html", form=AdminForm())


@admin.route("/hours", methods=['GET', 'POST'])
@login_required
def get_month_time():
    response = ""
    if request.method == 'POST':
        dict = request.form.to_dict()
        response = get_hours(dict['rf_id'])
    return render_template("month_times.html", form=RF_IDForm(), response=response)

views/views.py
from flask import Blueprint, render_template, request
from local_logging import logger
from views.forms import RegistrationForm, LimitForm
from controllers.controllers import register_user, get_recent_passes, get_fun, get_locations

views = Blueprint('views', __name__, template_folder='..templates')


@views.route("/", methods=['GET', 'POST'])
@views.route("/index", methods=['GET', 'POST'])
def index():
    limit = 10
    if request.method == 'POST':
        logger.info(request.form)
        limit = int(request.form['amount'])
    passes_data = get_recent_passes(limit)
    return render_template('index.html', passes_data=passes_data, form=LimitForm())


@views.route("/registration", methods=['GET', 'POST'])
def registration():
    logger.debug(request.method)
    if request.method == 'POST':
        request_data = request.form
        register_user(request_data)
        logger.info(request_data)
    return render_template('registration.html', form=RegistrationForm())


@views.route("/fun")
def kill_yourself():
    msg, result = get_fun()
    return render_template("easter_result.html", msg=msg, result=result)


@views.route("/locations")
def locate_users():
    location_data = get_locations()
    return render_template("locations.html", location_data=location_data)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header class="header">ghr</header>
</body>
</html>

templates/easter_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>{{ msg }}</p>
    <img
    {% if result %}
        src="static/images/dropped.jpg"
    {% else %}
        src="static/images/pineapple.jpg"
    {% endif %}
    alt="">
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Title</title><link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body>
  <header class="header">
      <a href="{{ url_for('views.locate_users') }}" class="button">
          Посмотреть местонахождение сотрудников
      </a>
      <a href="{{ url_for('views.registration') }}" class="button">
          Зарегистрировать сотрудника
      </a>
      <a href="{{ url_for('admin.get_month_time') }}" class="button">
          Посмотреть количество часов проведнных сотрудником на работе
      </a>
  </header>
    {% for message in get_flashed_messages() %}
    <div>{{ message }}</div>
    {% endfor %}
    <form action="/index" method="post">
        {{ form.hidden_tag() }}
        <div class ="number-input">{{ form.amount.label() }} {{ form.amount(class_="number") }}</div>
        {{ form.submit(class_="btn") }}
    </form>
    {% for pass in passes_data %}
        <div class="passes">
            <p>{{ pass[3] }} {{ pass[1] }} {{ pass[2] }}</p> <p>{{ pass[6] }}</p>
        </div>
    {% endfor %}
  </body>
</html>

templates/locations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for location in location_data %}
        {% if location[2] != "Администратор" %}
        <p>{{ location[1] }} {{ location[2] }}: {{ location[5] }}</p>
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('views.index') }}">Вернуться на главную страницу</a><br>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="/login" method="post">
        {{ form.hidden_tag() }}
        <p>{{ form.rf_id.label() }} {{ form.rf_id() }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}
    <a href="{{ url_for('views.index') }}">Вернуться на главную страницу</a><br>
</body>
</html>

templates/month_times.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="/hours" method="post">
        {{ form.hidden_tag() }}
        <p>{{ form.rf_id.label() }} {{ form.rf_id() }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    {{ response }}
</body>
</html>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Вы ввели неправильный адрес. Вернуться на <a href="{{ url_for("views.index") }}">главную страницу</a>?
</body>
</html>

templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="/registration" method="post">
        {{ form.hidden_tag() }}
        <p>{{ form.l_name.label() }} {{ form.l_name() }}</p>
        <p>{{ form.f_name.label() }} {{ form.f_name() }}</p>
        <p>{{ form.m_name.label() }} {{ form.m_name() }}</p>
        <p>{{ form.rf_id.label() }} {{ form.rf_id() }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <a href="{{ url_for('views.index') }}">Вернуться на главную страницу</a><br>
</body>
</html>

templates/unauthorized.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    У вас нет прав доступа. <a href="{{ url_for("admin.login_admin") }}">Войти как админимстратор</a>?
</body>
</html>